//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_Assignment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SLTechsModelContainer : DbContext
    {
        public SLTechsModelContainer()
            : base("name=SLTechsModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Skill> SkillSet { get; set; }
        public virtual DbSet<Course> CourseSet { get; set; }
        public virtual DbSet<Image> ImageSet { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Student> StudentSet { get; set; }
        public virtual DbSet<Rating> RatingSet { get; set; }
    }
}
